name: goreleaser

on:
  push:
    branches:
      - custom/ffmpeg-build

permissions:
  contents: read
  packages: write

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - name: Install go-swagger
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: go-swagger/go-swagger
          extension-matching: disable
          rename-to: swagger
          chmod: 0755
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
      - name: Push container images
        run: |
          docker push ghcr.io/parkour-vienna/gotosocial:snapshot-armv6
          docker push ghcr.io/parkour-vienna/gotosocial:snapshot-armv7
          docker push ghcr.io/parkour-vienna/gotosocial:snapshot-arm64v8
          docker push ghcr.io/parkour-vienna/gotosocial:snapshot-amd64
          docker manifest create ghcr.io/parkour-vienna/gotosocial:snapshot ghcr.io/parkour-vienna/gotosocial:snapshot-armv6 ghcr.io/parkour-vienna/gotosocial:snapshot-armv7 ghcr.io/parkour-vienna/gotosocial:snapshot-amd64 ghcr.io/parkour-vienna/gotosocial:snapshot-arm64v8
          docker manifest push ghcr.io/parkour-vienna/gotosocial:snapshot
